sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- python setup.py install
- echo "Installation complete."
cache: pip
script:
- python tests.py
deploy:
  skip_cleanup: true
  provider: pypi
  distributions: bdist_wheel
  user: freelawproject
  password:
    secure: BA57h240LQiycp1G+3VIGbscOkXHCRBGG78iujigMerVrulPGt7KaCC7c9GKoxjpMzITk4yRm/+E6aRCscSLOfD7p6+dO8k+CI8XR4n0pRiIMNZVV+7DJCA9tV6cAsNV/32JN2WVmEdrKhmijYS47HipndsYMW8dgz13wf92xW4=
  on:
    tags: true
